version: '3.8'
services:

  web:
    image: app-angular
    build:
      context: ./parc
      args:
        MY_UID: ${MY_UID:-1000}
        MY_GID: ${MY_GID:-1000}
    command: sh ./init-angular.sh
    volumes:
      - ./parc:/home/node/app
    ports: [ "4200:4200" ]
    restart: always

  api:
    image: app-python
    build:
      context: ./python
    volumes:
      - ./python:/var/www/html/back
    ports: [ "5001:5000" ]
    restart: always
    depends_on:
      - database

  database:
    image: mariadb:latest
    volumes:
      - database_data:/var/lib/mariadb/data:rw
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=parc
      - MYSQL_USER=mysqlusr
      - MYSQL_PASSWORD=mysqlpwd
    restart: always

volumes:
  database_data:
